import pymysql
from pathlib import Path
import os  # isort:skip


BASE_DIR = os.path.dirname(os.path.dirname(__file__))
pymysql.install_as_MySQLdb()
def gettext(s): return s


DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for ideaDC project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g8z$^$1_9-hry0@#s#85_vht*wi1$t*-wr&link+nkkm1=*15g'
# Salt for signing Single Sign On tokens
SSO_SALT = ''
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
PRODUCTION = True

ALLOWED_HOSTS = ['*']


# Application definition


ROOT_URLCONF = 'ideaDC.urls'


WSGI_APPLICATION = 'ideaDC.wsgi.application'

SESSION_COOKIE_NAME = 'session_id_new'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, '/static/')


SITE_ID = 2


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ideaDC', 'templates'), os.path.join(BASE_DIR, 'ideaDC/templates', 'allauth')],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.request',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = 'user.User'
swappable = 'AUTH_USER_MODEL'

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'user',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_googlemap',
    'djangocms_video',
    'ideaDC',
    'allauth',
    'sslserver',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.amazon',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'crispy_forms',
    'corsheaders',
    'rest_framework',
    'home'
]

TEXT_ADDITIONAL_ATTRIBUTES = ('onclick', 'onkeyup','placeholder','onkeypress','submit','keydown','blur','onfocus','onblur','click','paste',"innerHTML","addEventListener","document","function", "const","getAttribute")

LANGUAGES = (
    # Customize this
    ('en', gettext('en')),
)

CMS_LANGUAGES = {
    # Customize this
    1: [
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'django.core.context_processors.i18n',
    'django.core.context_processors.request',
    'django.core.context_processors.media',
    'django.core.context_processors.static',
    'sekizai.context_processors.sekizai',
    'cms.context_processors.cms_settings',
)


CMS_TEMPLATES = (
    # Customize this
    ("base.html", 'Base Page'),
    ("home/contact-us.html", 'Contact Page'),
    ("home/privacy-policy.html", 'Privacy Policy'),
    ("home/product.html", 'Product Page'),
    ("home/pricing.html", 'Pricing Page'),
    ("home/support.html", 'Support Page'),
    ("home/video.html", 'Video Page'),
    ("allauth/account/login.html", "Login Page"),
    ("allauth/account/signup.html", "Signup Page"),
    ("allauth/account/verifyaccount.html", "Verifyaccount Page"),
    ("allauth/account/otp.html", "OTP Page"),
    ("allauth/account/password_change.html", "Password Change Page"),
    ("allauth/account/password_reset_confirm.html", "Password Reset Confirm Page"),
    ("allauth/account/password_reset.html", "Password Reset Page"),
    ("error_404.html", "Error Page"),
    ('fullwidth.html', 'Fullwidth'),
    
)

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
AUTH_USER_EMAIL_UNIQUE = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
SILENCED_SYSTEM_CHECKS = ["auth.W004"]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False


CORS_ORIGIN_ALLOW_ALL = True

GOOGLE_RECAPTCHA_SITE_KEY = '6LfGT3saAAAAAJmXQL4V7671fZSP4LEeWyscal21'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LfGT3saAAAAABdPM8TWSQeLGburX9Y0iIyY3Qcl'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"
EMAIL_HOST_USER = "AKIAVRGD5TPIAWIXZXXK"
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = "BE3I5Q4VcVMvr/2/2jE6uDYFUhMGa7jwcEvyw4oqXK0H"
EMAIL_FROM = "support@ideadc.com"
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "support@ideadc.com"
TLS_Wrapper_Port = 465


# SESSION_COOKIE_AGE =(1 * 365 * 30 * 24 * 60 * 60)

TWILIO = {
    'TWILIO_ACCOUNT_SID': 'ACc4cc40a848c7509ec2001c5e68509d22',
    'TWILIO_AUTH_TOKEN': '54af6afe03224ae1fbc6fafa8d2ce6d7',
    'TWILIO_NUMBER': '+1 929 357 2170',
}

X_FRAME_OPTIONS = 'SAMEORIGIN'

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}


if PRODUCTION:
    DATABASES = {
        'default': {
            'CONN_MAX_AGE': 0,
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '163.123.196.6',
            'NAME': 'idea_dc',
            'PASSWORD': 'LkIdRG1CV2rV',
            'PORT': '3306',
            'USER': 'root'
        }
        # 'default': {
        #     'CONN_MAX_AGE': 0,
        #     'ENGINE': 'django.db.backends.mysql',
        #     'HOST': 'staging.2excel.com.au',
        #     'NAME': 'excelcrm_ideaDC',
        #     'PASSWORD': '2excel@1212',
        #     'PORT': '3306',
        #     'USER': 'pythone2excel'
        # }
    }
    URL = "https://ideadc.com"
    # URL = "https://staging.2excel.com.au:7676"
    

else:
    DATABASES = {
        'default': {
            'CONN_MAX_AGE': 0,
            'ENGINE': 'django.db.backends.sqlite3',
            'HOST': 'localhost',
            'NAME': 'project.db',
            'PASSWORD': '',
            'PORT': '',
            'USER': ''
        }
    }
    URL = "http://127.0.0.1:8000"

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'

        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'kr_KR',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v7.0',
    },
    'linkedin_oauth2': {
        'SCOPE': [
            'r_liteprofile',
            'r_emailaddress'
        ],
        'PROFILE_FIELDS': [
            'id',
            'first-name',
            'last-name',
            'email-address',
            'picture-url',
            'public-profile-url',
        ],

    },
    "apple": {
        "APP": {
            # Your service identifier.
            "client_id": "com.ideadc.signupapp",

            # The Key ID (visible in the "View Key Details" page).
            "secret": "6J495BYKKU",

            # Member ID/App ID Prefix -- you can find it below your name
            # at the top right corner of the page, or it’s your App ID
            # Prefix in your App ID.
            "key": "HKQG3S6SU9",

            # The certificate you downloaded when generating the key.
            "certificate_key": """-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVT/hHg0D8RFO6oCJ
DxnBaZ+117CDKfN7OkGlf+c1ktCgCgYIKoZIzj0DAQehRANCAASwBAWLLeQku7bL
og5zgSfbtnP4wbA3gv0uyRCiwMfFDCisyJvJTIKupFdxE8vyLiR3QWTDGQrUeG/A
owPCcPi1
-----END PRIVATE KEY-----
"""
        }
    }
}


SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60
